/*
 * LDRSensor.cpp
 *
 *  Created on: Jul 4, 2025
 *      Author: ADE1HYD
 */

#include "LdrSensor.hpp"

LdrSensor::LdrSensor(ADC_HandleTypeDef* adcHandle, uint32_t adcChannel)
    : _adcHandle(adcHandle), _adcChannel(adcChannel) {}

HAL_StatusTypeDef LdrSensor::init() {
    // This driver assumes the ADC peripheral itself (e.g., ADC1) has already
    // been initialized by the code generated by STM32CubeMX (MX_ADC1_Init()).
    // This function configures the specific channel for the sensor.
    ADC_ChannelConfTypeDef sConfig = {0};

    sConfig.Channel = _adcChannel;
    sConfig.Rank = 1; // Set rank to 1 for single conversion
    sConfig.SamplingTime = ADC_SAMPLETIME_84CYCLES; // A moderate sampling time

    return HAL_ADC_ConfigChannel(_adcHandle, &sConfig);
}

uint16_t LdrSensor::getRawValue() {
    // Select the channel to be converted
    ADC_ChannelConfTypeDef sConfig = {0};
    sConfig.Channel = _adcChannel;
    sConfig.Rank = 1;
    sConfig.SamplingTime = ADC_SAMPLETIME_84CYCLES;
    if (HAL_ADC_ConfigChannel(_adcHandle, &sConfig) != HAL_OK) {
        // Handle error, perhaps return a specific error code
        return 0;
    }

    // Start the ADC conversion
    if (HAL_ADC_Start(_adcHandle) != HAL_OK) {
        return 0; // Start failed
    }

    // Wait for the conversion to complete with a timeout
    if (HAL_ADC_PollForConversion(_adcHandle, 10) == HAL_OK) {
        // Read and return the converted value
        uint16_t value = HAL_ADC_GetValue(_adcHandle);
        HAL_ADC_Stop(_adcHandle); // Stop the ADC
        return value;
    }

    HAL_ADC_Stop(_adcHandle); // Stop on timeout failure
    return 0; // Conversion failed
}

float LdrSensor::getLightPercentage() {
    uint16_t rawValue = getRawValue();
    // NEW: Invert the reading by subtracting it from the maximum value
    return ((4095.0f - static_cast<float>(rawValue)) / 4095.0f) * 100.0f;
}


